[package]
name = "sol_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.14.3"
solana-program-test = "1.14.3"
spl-token = "3.5.0"
